### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by CloudeLecaw** [10becja/ChessCraft#4]
Would be nice to have a 1.13 compatiblity.

I tested it and it does not load correctly anmore in 1.13 :\

Error on Loading:
```
[12:59:07] [Server thread/INFO]: [ChessCraft] Enabling ChessCraft v3.0.2-SNAPSHOT
[12:59:07] [Server thread/WARN]: java.lang.ClassNotFoundException: me.desht.chesscraft.dhutils.nms.v1_13_R1.NMSHandler
[12:59:07] [Server thread/WARN]: 	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
[12:59:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154)
[12:59:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
[12:59:07] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
[12:59:07] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
[12:59:07] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[12:59:07] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Unknown Source)
[12:59:07] [Server thread/WARN]: 	at me.desht.chesscraft.dhutils.nms.NMSHelper.init(NMSHelper.java:44)
[12:59:07] [Server thread/WARN]: 	at me.desht.chesscraft.dhutils.nms.NMSHelper.init(NMSHelper.java:23)
[12:59:07] [Server thread/WARN]: 	at me.desht.chesscraft.ChessCraft.onEnable(ChessCraft.java:80)
[12:59:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[12:59:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
[12:59:07] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[12:59:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:426)
[12:59:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:340)
[12:59:07] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:562)
[12:59:07] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:524)
[12:59:07] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:423)
[12:59:07] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288)
[12:59:07] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686)
[12:59:07] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
[12:59:07] [Server thread/ERROR]: [ChessCraft] ChessCraft version 3.0.2-SNAPSHOT is not compatible with this CraftBukkit version.
[12:59:07] [Server thread/ERROR]: [ChessCraft] Check http://dev.bukkit.org/server-mods/chesscraft for information on updated builds.
[12:59:07] [Server thread/ERROR]: [ChessCraft] Plugin disabled.
```

**Comment by Peda1996** [comment]
The problem is within the dhutils, and thats pretty hard to update..
It would be very cool if the author could upgrade this ^^

**Comment by 10becja** [comment]
My apologies on taking so very long to respond. I've more or less moved on from developing/maintaining minecraft plugins as I simply don't have the time for it anymore, so I probably won't be getting to updating this any time soon.
